# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['twitter_crawler_ui.py'],
    pathex=[],
    binaries=[('chromedriver.exe', '.')],
    datas=[
        ('X_cookie.json', '.'),
        ('config.py', '.'),
        ('README.md', '.'),
        ('requirements.txt', '.'),
        ('set_cookie.py', '.'),
        ('twitter_Crawler.py', '.'),
        ('main.py', '.'),
        ('download_method.py', '.'),
        ('driver_init.py', '.'),
        ('json_process.py', '.'),
        ('manga_downloader.py', '.'),
        ('save_image_urls.py', '.'),
        ('saveDZ_crawler.py', '.'),
        ('注意事项.txt', '.'),
        ('LICENSE.chromedriver', '.'),
        ('THIRD_PARTY_NOTICES.chromedriver', '.')
    ],
    hiddenimports=[
        'PyQt6',
        'selenium',
        'datetime',
        'json',
        'logging',
        'pathlib',
        'set_cookie',
        'twitter_Crawler',
        'main',
        'download_method',
        'driver_init',
        'json_process',
        'manga_downloader',
        'save_image_urls',
        'saveDZ_crawler',
        'requests',
        'termcolor',
        'tenacity',
        'urllib3',
        'psutil',
        'tempfile',
        'shutil',
        'glob',
        'threading',
        'queue',
        'signal',
        # 添加自动下载ChromeDriver的依赖
        'webdriver_manager',
        'webdriver_manager.chrome',
        # Windows环境下可能需要的额外依赖
        'win32api',
        'win32con',
        'win32gui',
        'selenium.webdriver.chrome.service',
        'importlib.metadata',
        'packaging',
        'packaging.version'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Twitter爬虫',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico' if os.path.exists('icon.ico') else None,
) 